using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace PubSub.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class PubSubDispatcherGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var pubSubTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "PubSub.PubSubTopicAttribute",
                predicate: static (_, _) => true,
                transform: static (ctx, _) => ctx.TargetSymbol as INamedTypeSymbol)
            .Where(static s => s is not null)
            .Collect()
            .Select(static (arr, _) => arr
                .Where(static s => s is not null)
                .Cast<INamedTypeSymbol>()
                .Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default)
                .OrderBy(static s => s.ToDisplayString(), System.StringComparer.Ordinal)
                .ToImmutableArray());

        context.RegisterSourceOutput(pubSubTypes, GenerateSource);
    }

    private static void GenerateSource(SourceProductionContext ctx, ImmutableArray<INamedTypeSymbol> types)
    {
        if (types.IsDefaultOrEmpty) return;

        var seenNames = new HashSet<string>();
        var emitted = new List<(INamedTypeSymbol Symbol, string SafeName, IMethodSymbol? Ctor)>();
        foreach (var t in types)
        {
            var baseName = SafeIdent(t.Name);
            var name = baseName;
            var i = 2;
            while (!seenNames.Add(name)) { name = baseName + "_" + i++; }
            var ctor = PickPrimaryConstructor(t);
            emitted.Add((t, name, ctor));
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using System.Text.Json.Serialization.Metadata;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using PubSub;");
        sb.AppendLine();
        sb.AppendLine("namespace PubSub.Generated;");
        sb.AppendLine();

        EmitContext(sb, emitted);
        sb.AppendLine();

        foreach (var (t, name, _) in emitted)
        {
            var fqn = t.ToDisplayString();
            sb.AppendLine($"internal sealed class PubSubDispatcher_{name} : IPubSubDispatcher<{fqn}>");
            sb.AppendLine("{");
            sb.AppendLine($"    public static readonly PubSubDispatcher_{name} Instance = new();");
            sb.AppendLine($"    private static readonly JsonTypeInfo<{fqn}> s_typeInfo = PubSubJsonContext.Default.{name};");
            sb.AppendLine($"    public byte[] Serialize({fqn} message) => JsonSerializer.SerializeToUtf8Bytes(message, s_typeInfo);");
            sb.AppendLine($"    public {fqn} Deserialize(ReadOnlySpan<byte> body) => JsonSerializer.Deserialize(body, s_typeInfo)!;");
            sb.AppendLine($"    public Task InvokeAsync(ISubscribeTo<{fqn}> handler, {fqn} message, CancellationToken cancellationToken) => handler.Handle(message, cancellationToken);");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("internal static class PubSubGeneratedRegistrar");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");
        foreach (var (t, name, _) in emitted)
        {
            var fqn = t.ToDisplayString();
            sb.AppendLine($"        PubSubDispatcherRegistry.Register<{fqn}>(PubSubDispatcher_{name}.Instance);");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("PubSubDispatchers.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitContext(StringBuilder sb, List<(INamedTypeSymbol Symbol, string SafeName, IMethodSymbol? Ctor)> emitted)
    {
        sb.AppendLine("internal sealed class PubSubJsonContext : JsonSerializerContext");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly DefaultJsonTypeInfoResolver s_reflectionFallback = new();");
        sb.AppendLine("    private static readonly JsonSerializerOptions s_options = BuildOptions();");
        sb.AppendLine("    private static PubSubJsonContext? s_default;");
        sb.AppendLine("    public static PubSubJsonContext Default => s_default ??= new PubSubJsonContext();");
        sb.AppendLine("    public PubSubJsonContext() : base(s_options) { }");
        sb.AppendLine("    public PubSubJsonContext(JsonSerializerOptions? options) : base(options ?? s_options) { }");
        sb.AppendLine("    protected override JsonSerializerOptions? GeneratedSerializerOptions => s_options;");
        sb.AppendLine();
        sb.AppendLine("    private static JsonSerializerOptions BuildOptions()");
        sb.AppendLine("    {");
        sb.AppendLine("        var opts = new JsonSerializerOptions(JsonSerializerDefaults.Web);");
        sb.AppendLine("        opts.TypeInfoResolverChain.Add(s_reflectionFallback);");
        sb.AppendLine("        return opts;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public override JsonTypeInfo? GetTypeInfo(Type type)");
        sb.AppendLine("    {");
        foreach (var (t, name, _) in emitted)
        {
            sb.AppendLine($"        if (type == typeof({t.ToDisplayString()})) return {name};");
        }
        sb.AppendLine("        return s_reflectionFallback.GetTypeInfo(type, s_options);");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var (t, name, ctor) in emitted)
        {
            var fqn = t.ToDisplayString();
            sb.AppendLine($"    private JsonTypeInfo<{fqn}>? _{name};");
            sb.AppendLine($"    public JsonTypeInfo<{fqn}> {name} => _{name} ??= Create_{name}();");
            sb.AppendLine($"    private JsonTypeInfo<{fqn}> Create_{name}()");
            sb.AppendLine("    {");
            sb.AppendLine($"        var values = new JsonObjectInfoValues<{fqn}>");
            sb.AppendLine("        {");

            var props = ctor is not null
                ? GetPropertiesForConstructor(t, ctor)
                : t.GetMembers().OfType<IPropertySymbol>().Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && p.GetMethod is not null).ToList();

            if (ctor is not null && ctor.Parameters.Length > 0)
            {
                sb.Append($"            ObjectWithParameterizedConstructorCreator = static args => new {fqn}(");
                for (var i = 0; i < ctor.Parameters.Length; i++)
                {
                    var p = ctor.Parameters[i];
                    sb.Append(CastArg(p.Type, i));
                    if (i < ctor.Parameters.Length - 1) sb.Append(", ");
                }
                sb.AppendLine("),");
                sb.AppendLine("            ConstructorParameterMetadataInitializer = static () => new JsonParameterInfoValues[]");
                sb.AppendLine("            {");
                for (var i = 0; i < ctor.Parameters.Length; i++)
                {
                    var p = ctor.Parameters[i];
                    sb.AppendLine($"                new JsonParameterInfoValues {{ Name = \"{p.Name}\", ParameterType = typeof({TypeOfRef(p.Type)}), Position = {i}, HasDefaultValue = {(p.HasExplicitDefaultValue ? "true" : "false")}, DefaultValue = {DefaultLiteral(p)} }},");
                }
                sb.AppendLine("            },");
            }
            else
            {
                sb.AppendLine($"            ObjectCreator = static () => System.Activator.CreateInstance<{fqn}>()!,");
            }

            sb.AppendLine("            PropertyMetadataInitializer = static _ => new JsonPropertyInfo[]");
            sb.AppendLine("            {");
            foreach (var p in props)
            {
                var propTypeRef = TypeRef(p.Type);
                var hasSetter = p.SetMethod is not null
                    && p.SetMethod.DeclaredAccessibility == Accessibility.Public
                    && !p.SetMethod.IsInitOnly;
                sb.AppendLine($"                JsonMetadataServices.CreatePropertyInfo<{propTypeRef}>(s_options, new JsonPropertyInfoValues<{propTypeRef}>");
                sb.AppendLine("                {");
                sb.AppendLine("                    IsProperty = true,");
                sb.AppendLine("                    IsPublic = true,");
                sb.AppendLine("                    IsVirtual = false,");
                sb.AppendLine($"                    DeclaringType = typeof({fqn}),");
                sb.AppendLine("                    Converter = null,");
                sb.AppendLine($"                    Getter = static obj => (({fqn})obj).{p.Name},");
                if (hasSetter)
                    sb.AppendLine($"                    Setter = static (obj, value) => (({fqn})obj).{p.Name} = value!,");
                else
                    sb.AppendLine("                    Setter = null,");
                sb.AppendLine("                    IgnoreCondition = null,");
                sb.AppendLine("                    HasJsonInclude = false,");
                sb.AppendLine("                    IsExtensionData = false,");
                sb.AppendLine("                    NumberHandling = null,");
                sb.AppendLine($"                    PropertyName = \"{p.Name}\",");
                sb.AppendLine($"                    JsonPropertyName = null,");
                sb.AppendLine("                }),");
            }
            sb.AppendLine("            },");
            sb.AppendLine("        };");
            sb.AppendLine($"        return JsonMetadataServices.CreateObjectInfo<{fqn}>(s_options, values);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    private static IMethodSymbol? PickPrimaryConstructor(INamedTypeSymbol t)
    {
        var ctors = t.InstanceConstructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public)
            .OrderByDescending(c => c.Parameters.Length)
            .ToList();
        return ctors.FirstOrDefault(c => c.Parameters.Length > 0) ?? ctors.FirstOrDefault();
    }

    private static List<IPropertySymbol> GetPropertiesForConstructor(INamedTypeSymbol t, IMethodSymbol ctor)
    {
        var props = t.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && p.GetMethod is not null)
            .ToList();
        if (ctor.Parameters.Length == 0) return props;
        var byName = new Dictionary<string, IPropertySymbol>(System.StringComparer.OrdinalIgnoreCase);
        foreach (var p in props) byName[p.Name] = p;
        var ordered = new List<IPropertySymbol>(ctor.Parameters.Length);
        foreach (var p in ctor.Parameters)
        {
            if (byName.TryGetValue(p.Name, out var prop))
                ordered.Add(prop);
        }
        foreach (var p in props)
        {
            if (!ordered.Contains(p)) ordered.Add(p);
        }
        return ordered;
    }

    private static string CastArg(ITypeSymbol t, int index)
    {
        var typeRef = TypeRef(t);
        return $"({typeRef})args[{index}]!";
    }

    private static string TypeRef(ITypeSymbol t) => t.ToDisplayString();

    /// <summary>
    /// The same type reference with any nullable-reference annotation dropped: <c>typeof</c> rejects
    /// <c>T?</c> for a reference type (CS8639), so a message whose constructor takes a nullable
    /// reference parameter would otherwise emit source that does not compile.
    /// </summary>
    private static string TypeOfRef(ITypeSymbol t) =>
        t.NullableAnnotation == NullableAnnotation.Annotated && t.IsReferenceType
            ? t.WithNullableAnnotation(NullableAnnotation.None).ToDisplayString()
            : TypeRef(t);

    /// <summary>
    /// Emits the parameter's default as a literal assigned to <c>JsonParameterInfoValues.DefaultValue</c>,
    /// which is typed <c>object</c>. The literal must therefore box the parameter's OWN type: a bare
    /// <c>0</c> for a <c>long</c> parameter boxes an <see cref="int"/>, and <c>JsonParameterInfo&lt;long&gt;</c>
    /// throws <c>InvalidCastException</c> when it unboxes. Numerics and enums are cast explicitly for that
    /// reason, and formatted with <see cref="CultureInfo.InvariantCulture"/> because the result is C# source,
    /// not display text.
    /// </summary>
    private static string DefaultLiteral(IParameterSymbol p)
    {
        if (!p.HasExplicitDefaultValue) return "null";

        var v = p.ExplicitDefaultValue;
        return v switch
        {
            null => "null",
            string s => $"\"{s.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"",
            bool b => b ? "true" : "false",
            char c => $"'{c}'",
            double d => TypedLiteral(p, DoubleLiteral(d)),
            float f => TypedLiteral(p, SingleLiteral(f)),
            decimal m => TypedLiteral(p, m.ToString(CultureInfo.InvariantCulture) + "m"),
            IFormattable n => TypedLiteral(p, n.ToString(null, CultureInfo.InvariantCulture)),
            _ => "null",
        };
    }

    private static string TypedLiteral(IParameterSymbol p, string literal) => $"({TypeRef(p.Type)})({literal})";

    private static string DoubleLiteral(double d)
    {
        if (double.IsNaN(d)) return "double.NaN";
        if (double.IsPositiveInfinity(d)) return "double.PositiveInfinity";
        if (double.IsNegativeInfinity(d)) return "double.NegativeInfinity";
        return d.ToString("R", CultureInfo.InvariantCulture) + "D";
    }

    private static string SingleLiteral(float f)
    {
        if (float.IsNaN(f)) return "float.NaN";
        if (float.IsPositiveInfinity(f)) return "float.PositiveInfinity";
        if (float.IsNegativeInfinity(f)) return "float.NegativeInfinity";
        return f.ToString("R", CultureInfo.InvariantCulture) + "F";
    }

    private static string SafeIdent(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var c in name)
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        if (sb.Length == 0 || char.IsDigit(sb[0])) sb.Insert(0, '_');
        return sb.ToString();
    }
}
