<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PubSub.Pulse.Sample</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PubSub\PubSub.csproj" />
    <ProjectReference Include="..\..\src\PubSub.RabbitMQ\PubSub.RabbitMQ.csproj" />
    <ProjectReference Include="..\..\src\PubSub.Pulse\PubSub.Pulse.csproj" />
    <ProjectReference Include="..\..\src\PubSub.SourceGenerators\PubSub.SourceGenerators.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
